// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM2l3kytsBI_5ZslROJcDaOw5T8tCr4eQ',
    appId: '1:997257947847:web:c14e3df39f15754a1d2ce2',
    messagingSenderId: '997257947847',
    projectId: 'books-store-69ba9',
    authDomain: 'books-store-69ba9.firebaseapp.com',
    storageBucket: 'books-store-69ba9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXFVGnzCLYq9v6fDjnoaTyUAOb2nT6u74',
    appId: '1:997257947847:android:14ce30bd610fd7691d2ce2',
    messagingSenderId: '997257947847',
    projectId: 'books-store-69ba9',
    storageBucket: 'books-store-69ba9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwaDBsZ8BgNQb1qWXki7Lo0fkshxcwUhM',
    appId: '1:997257947847:ios:ebabf7468f7d63cd1d2ce2',
    messagingSenderId: '997257947847',
    projectId: 'books-store-69ba9',
    storageBucket: 'books-store-69ba9.appspot.com',
    iosBundleId: 'com.example.booksGallery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwaDBsZ8BgNQb1qWXki7Lo0fkshxcwUhM',
    appId: '1:997257947847:ios:6bec8442d7133b701d2ce2',
    messagingSenderId: '997257947847',
    projectId: 'books-store-69ba9',
    storageBucket: 'books-store-69ba9.appspot.com',
    iosBundleId: 'com.example.booksGallery.RunnerTests',
  );
}
